2025-08-08 06:22:57,476 INFO: OMNIDESK startup [in /home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/__init__.py:44]
2025-08-08 06:24:24,110 INFO: OMNIDESK startup [in /home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/__init__.py:44]
2025-08-08 06:24:24,143 INFO: OMNIDESK startup [in /home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/__init__.py:44]
2025-08-08 06:24:24,143 INFO: OMNIDESK startup [in /home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/__init__.py:44]
2025-08-08 06:28:15,990 INFO: OMNIDESK startup [in /home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/__init__.py:44]
2025-08-08 06:28:16,018 INFO: OMNIDESK startup [in /home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/__init__.py:44]
2025-08-08 06:28:16,018 INFO: OMNIDESK startup [in /home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/__init__.py:44]
2025-08-08 06:28:43,103 INFO: OMNIDESK startup [in /home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/__init__.py:44]
2025-08-08 06:28:43,127 INFO: OMNIDESK startup [in /home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/__init__.py:44]
2025-08-08 06:28:43,127 INFO: OMNIDESK startup [in /home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/__init__.py:44]
2025-08-08 18:48:59,106 INFO: OMNIDESK startup [in /home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/__init__.py:44]
2025-08-08 18:48:59,141 INFO: OMNIDESK startup [in /home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/__init__.py:44]
2025-08-08 18:48:59,141 INFO: OMNIDESK startup [in /home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/__init__.py:44]
2025-08-08 19:30:10,094 INFO: OMNIDESK startup [in /home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/__init__.py:44]
2025-08-08 19:31:54,585 INFO: OMNIDESK startup [in /home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/__init__.py:44]
2025-08-08 19:31:54,624 INFO: OMNIDESK startup [in /home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/__init__.py:44]
2025-08-08 19:31:54,624 INFO: OMNIDESK startup [in /home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/__init__.py:44]
2025-08-08 19:37:38,335 INFO: OMNIDESK startup [in /home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/__init__.py:44]
2025-08-08 19:37:38,373 INFO: OMNIDESK startup [in /home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/__init__.py:44]
2025-08-08 19:37:38,373 INFO: OMNIDESK startup [in /home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/__init__.py:44]
2025-08-08 19:46:51,588 INFO: OMNIDESK startup [in /home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/__init__.py:44]
2025-08-08 19:46:51,626 INFO: OMNIDESK startup [in /home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/__init__.py:44]
2025-08-08 19:46:51,626 INFO: OMNIDESK startup [in /home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/__init__.py:44]
2025-08-08 19:49:22,308 INFO: OMNIDESK startup [in /home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/__init__.py:44]
2025-08-08 19:49:43,944 INFO: OMNIDESK startup [in /home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/__init__.py:44]
2025-08-08 19:50:27,120 ERROR: Exception on /reset_password_request [POST] [in /home/k4r4b0/Desktop/Projects/Python/Omnidesk/venv/lib/python3.13/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/k4r4b0/Desktop/Projects/Python/Omnidesk/venv/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/k4r4b0/Desktop/Projects/Python/Omnidesk/venv/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/k4r4b0/Desktop/Projects/Python/Omnidesk/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/k4r4b0/Desktop/Projects/Python/Omnidesk/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/routes.py", line 84, in reset_password_request
    send_password_reset_email(user)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/email.py", line 25, in send_password_reset_email
    from app import mail
ImportError: cannot import name 'mail' from 'app' (/home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/__init__.py). Did you mean: 'email'?
2025-08-08 19:50:40,901 ERROR: Exception on /reset_password_request [POST] [in /home/k4r4b0/Desktop/Projects/Python/Omnidesk/venv/lib/python3.13/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/k4r4b0/Desktop/Projects/Python/Omnidesk/venv/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/k4r4b0/Desktop/Projects/Python/Omnidesk/venv/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/k4r4b0/Desktop/Projects/Python/Omnidesk/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/k4r4b0/Desktop/Projects/Python/Omnidesk/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/routes.py", line 84, in reset_password_request
    send_password_reset_email(user)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/email.py", line 25, in send_password_reset_email
    from app import mail
ImportError: cannot import name 'mail' from 'app' (/home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/__init__.py). Did you mean: 'email'?
2025-08-08 19:55:32,087 INFO: OMNIDESK startup [in /home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/__init__.py:44]
2025-08-08 19:57:32,920 ERROR: Exception on /reset_password_request [POST] [in /home/k4r4b0/Desktop/Projects/Python/Omnidesk/venv/lib/python3.13/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/k4r4b0/Desktop/Projects/Python/Omnidesk/venv/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/k4r4b0/Desktop/Projects/Python/Omnidesk/venv/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/k4r4b0/Desktop/Projects/Python/Omnidesk/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/k4r4b0/Desktop/Projects/Python/Omnidesk/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/routes.py", line 85, in reset_password_request
    send_password_reset_email(user)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/email.py", line 25, in send_password_reset_email
    from app import mail
ImportError: cannot import name 'mail' from 'app' (/home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/__init__.py). Did you mean: 'email'?
2025-08-08 20:00:00,884 INFO: OMNIDESK startup [in /home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/__init__.py:44]
2025-08-08 20:00:14,435 ERROR: Exception on /reset_password_request [POST] [in /home/k4r4b0/Desktop/Projects/Python/Omnidesk/venv/lib/python3.13/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/k4r4b0/Desktop/Projects/Python/Omnidesk/venv/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/k4r4b0/Desktop/Projects/Python/Omnidesk/venv/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/k4r4b0/Desktop/Projects/Python/Omnidesk/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/k4r4b0/Desktop/Projects/Python/Omnidesk/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/routes.py", line 85, in reset_password_request
    send_password_reset_email(user)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/email.py", line 19, in send_password_reset_email
    from app import mail
ImportError: cannot import name 'mail' from 'app' (/home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/__init__.py). Did you mean: 'email'?
2025-08-08 20:01:06,881 INFO: OMNIDESK startup [in /home/k4r4b0/Desktop/Projects/Python/Omnidesk/app/__init__.py:44]
